### PR TITLE
Added Timed Cross coverage

### PR DESCRIPTION
**Pull request by Dobios**
# Timed Cross Coverage  
__Idea__: We want to check the relationship between two ports with a delay of a certain amount of cycles.  
__Example__: We have the following situation, imagine we have a device that breaks if:    
- `dut.io.a` takes the value of `1.U` at cycle 1  
- `dut.io.b` takes the value of `1.U` the following cycle  

We want to verify that the above case was tested. This can be done by defining a `TimedCross` between the two points:  
```scala
        val cr = new CoverageReporter(dut)
        cr.register(
            //Declare CoverPoints
            CoverPoint(dut.io.a, "a")())::
            CoverPoint(dut.io.b, "b")())::
            Nil,
            //Declare timed cross point with a delay of 1 cycle
            TimedCross("timedAB", "a", "b", 1)(
                CrossBin("both1", 1 to 1, 1 to 1)::Nil)::
            Nil)
```  

Using that, we can check that we tested the above case in our test suite.  
This construct can be used to check delay between two cover points.  
  
## Use  
To be able to use the timed coverage, stepping the clock must be done through the coverage reporter:  
```scala
dut.clock.step(nCycles) //Will trigger an exception if used with Timed Cross Coverage
cr.step(nCycles) //Works
```  
This is done in order ensure that the coverage database will always remain synchronized with the DUT's internal clock.
  
## Future Development  
An idea would be to extend this construct to allow for special types of timing:  
- `Eventually`: This would see if a cross hit was detected at any point in the next given amount of cycles.  
- `Always`: This would only consider a hit if the it was detected every cycle in the next given amount of cycles.  
- `Exactly`: This is what the current implementation supports.  

A timed bin could then be declared as follows:  
```scala
abstract class DelayType  
case object Eventually extends DelayType
case object Always extends DelayType
case object Exactly extends DelayType
case class TimedCross(name: String, point1: String, point2: String, delay: Int, type: DelayType)(bins: List[CrossBin])

//Example
TimedCross("timedAB", "a", "b", 3, Exactly)(
    CrossBin("both1", 1 to 1, 1 to 1)::Nil)::
Nil) 
```

### CODE REVIEW

**Comment by schoeberl** [comment]
Very nice idea! Actually related to this: assertions with timing would also be nice. Two of my verification students are working on this. @Dobios I guess you know them.

However, I do not approve this PR. There are two issues:

 * Please do not commit the .idea folder and files in it, this is a local setup
 * You touched 28 files. I guess there was a substitution mistake and you probably broke something in the SV code.

**Comment by Dobios** [comment]
> Very nice idea! Actually related to this: assertions with timing would also be nice. Two of my verification students are working on this. @Dobios I guess you know them.
Yes I've spoken to Niels about it and it could be interesting to add that to the framework.    

> However, I do not approve this PR. There are two issues:
> 
> * Please do not commit the .idea folder and files in it, this is a local setup
> * You touched 28 files. I guess there was a substitution mistake and you probably broke something in the SV code.
Yes I accidentally committed and broke stuff last week, which I immediately fixed after (so the files I touched are actually just fixing something I broke last week if you look closely at the changes)

**Comment by schoeberl** [comment]
There are still the two files form .idea folder to drop.

**Comment by schoeberl** [comment]
My fault, the .idea files are deleted with this PR. LGTM.

**Pull request merged**
